import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

final lightTheme = FlexThemeData.light(
  colors: const FlexSchemeColor(
    primary: Color(0xffdbe1f0),
    primaryContainer: Color(0xffb7c1d2),
    secondary: Color(0xff768798),
    secondaryContainer: Color(0xff576a7a),
    tertiary: Color(0xff42515c),
    tertiaryContainer: Color(0xff283137),
    appBarColor: Color(0xff576a7a),
    error: Color(0xffb00020),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 7,
  appBarStyle: FlexAppBarStyle.primary,
  appBarOpacity: 0.90,
  bottomAppBarElevation: 11.5,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 10,
    blendOnColors: false,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 14.0,
    textButtonSchemeColor: SchemeColor.onPrimary,
    filledButtonRadius: 14.0,
    elevatedButtonRadius: 14.0,
    elevatedButtonSchemeColor: SchemeColor.tertiaryContainer,
    outlinedButtonRadius: 14.0,
    outlinedButtonSchemeColor: SchemeColor.tertiaryContainer,
    outlinedButtonBorderWidth: 1.0,
    outlinedButtonPressedBorderWidth: 1.5,
    checkboxSchemeColor: SchemeColor.primary,
    inputDecoratorSchemeColor: SchemeColor.secondary,
    inputDecoratorIsFilled: false,
    inputDecoratorBackgroundAlpha: 101,
    inputDecoratorBorderSchemeColor: SchemeColor.tertiaryContainer,
    inputDecoratorRadius: 14.0,
    inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
    fabUseShape: true,
    fabRadius: 18.0,
    fabSchemeColor: SchemeColor.primary,
    chipRadius: 14.0,
    popupMenuRadius: 6.0,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    bottomAppBarSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedLabelSchemeColor: SchemeColor.tertiaryContainer,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedIconSchemeColor: SchemeColor.tertiaryContainer,
    navigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationBarLabelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
);
final darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xfff0eadb),
    primaryContainer: Color(0xffd2c8b7),
    secondary: Color(0xff988776),
    secondaryContainer: Color(0xff7a6757),
    tertiary: Color(0xff5c4d42),
    tertiaryContainer: Color(0xff372e28),
    appBarColor: Color(0xff7a6757),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.levelSurfacesLowScaffold,
  blendLevel: 13,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 20,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    textButtonRadius: 14.0,
    textButtonSchemeColor: SchemeColor.onPrimary,
    filledButtonRadius: 14.0,
    elevatedButtonRadius: 14.0,
    elevatedButtonSchemeColor: SchemeColor.tertiaryContainer,
    outlinedButtonRadius: 14.0,
    outlinedButtonSchemeColor: SchemeColor.tertiaryContainer,
    outlinedButtonBorderWidth: 1.0,
    outlinedButtonPressedBorderWidth: 1.5,
    checkboxSchemeColor: SchemeColor.primary,
    inputDecoratorIsFilled: false,
    inputDecoratorRadius: 14.0,
    fabUseShape: true,
    fabRadius: 18.0,
    fabSchemeColor: SchemeColor.primary,
    chipRadius: 14.0,
    popupMenuRadius: 6.0,
    alignedDropdown: true,
    useInputDecoratorThemeInDialogs: true,
    bottomAppBarSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedLabelSchemeColor: SchemeColor.tertiaryContainer,
    navigationBarUnselectedLabelSchemeColor: SchemeColor.tertiary,
    navigationBarSelectedIconSchemeColor: SchemeColor.tertiaryContainer,
    navigationBarUnselectedIconSchemeColor: SchemeColor.tertiary,
    navigationBarLabelBehavior: NavigationDestinationLabelBehavior.onlyShowSelected,
  ),
  visualDensity: FlexColorScheme.comfortablePlatformDensity,
  useMaterial3: true,
  swapLegacyOnMaterial3: true,
  // To use the Playground font, add GoogleFonts package and uncomment
  // fontFamily: GoogleFonts.notoSans().fontFamily,
);
